### ISSUE TITLE
Port to Qt5

### ISSUE THREAD

**Issue by s8321414** [dos1/kamerka#26]
Please port to Qt5, Qt4 will be EOL soon.

**Comment by Knusper** [comment]
Although "me too" comments are discouraged... me too :love_letter:

**Comment by dos1** [comment]
I definitely have it on my TODO list, I just need to find some spare time for it :)

**Comment by s8321414** [comment]
@dos1 :+1:

**Comment by dos1** [comment]
I just pushed the initial port to `kf5` branch. It works, but has some glitches still left to fix. Shouldn't take too long though ;)

**Comment by dos1** [comment]
...and it's on `master`. I should make a release Very Soon Now™.

**Comment by akien-mga** [comment]
Bump for the release :)
In the meantime I'll package the current master branch for Mageia 6.

**Comment by dos1** [comment]
I've just released 0.20 ;D
