### ISSUE TITLE
qimageblitz is part of kdesupport, please do not use it as a standalone package

### ISSUE THREAD

**Issue by yurivict** [dos1/kamerka#28]
Changelog in this repository svn://anonsvn.kde.org/home/kde/trunk/kdesupport/qimageblitz says:
```
0.0.4:

* Blitz is now part of kdesupport. This tarball is a snapshot intended for
use with the production version of KDE 4.0. 
```

Also see it here: https://api.kde.org/kdesupport-api/kdesupport-apidocs/qimageblitz/html/blitz_8cpp.html

The standalone ```qimageblitz``` shouldn't exist at this point.

**Comment by dos1** [comment]
Well, that's where I'm getting it and was always getting it from (kdesupport repo). That's also where the AUR package points to. Distributions generally don't package kdesupport anymore, so I don't see anything worth changing in Kamerka when it comes to qimageblitz dependency (aside of maybe vendoring it, as it's unlikely to get any new release at this point).

**Comment by yurivict** [comment]
Ah, okay, I didn't realize that ```kdesupport``` isn't packaged and its components exist as individual packages.

**Comment by yurivict** [comment]
```qimageblitz``` is has seen its last update in 2010, with Qt4. The later changes have never been authorized by kde, and aren't officially released. There are no tarballs, only a subversion repository svn://anonsvn.kde.org/home/kde/trunk/kdesupport/qimageblitz

You should probably stop betting on unreleased software, and use something else. Or bundle it.

I created a FreeBSD port for ```qimageblitz``` and people complain that I brought some unmaintained, dubious software into the ports system.

**Comment by yurivict** [comment]
```kamarka``` is also the only user of ```qimageblitz```, see here https://aur.archlinux.org/packages/qimageblitz-svn/ (kde* items there are outdated, they exist only because they didn't remove kde4 yet).
